auto
/usr/include/db.h
db
/usr/include/db
db_185.h
/usr/include/db_185.h
db_cxx.h
/usr/include/db_cxx.h
libdb.a
/usr/lib/libdb.a
libdb.dll.a
/usr/lib/libdb.dll.a
libdb.la
/usr/lib/libdb.la
libdb_cxx.a
/usr/lib/libdb_cxx.a
libdb_cxx.dll.a
/usr/lib/libdb_cxx.dll.a
libdb_cxx.la
/usr/lib/libdb_cxx.la

/usr/include/db4.5/db.h
405
/usr/include/db4.5
/usr/include/db4.5/db_185.h
/usr/include/db4.5/db_cxx.h
/usr/lib/libdb-4.5.a
/usr/lib/libdb-4.5.dll.a
/usr/lib/libdb-4.5.la
/usr/lib/libdb_cxx-4.5.a
/usr/lib/libdb_cxx-4.5.dll.a
/usr/lib/libdb_cxx-4.5.la
/usr/include/db4.8/db.h
408
/usr/include/db4.8
/usr/include/db4.8/db_185.h
/usr/include/db4.8/db_cxx.h
/usr/lib/libdb-4.8.a
/usr/lib/libdb-4.8.dll.a
/usr/lib/libdb-4.8.la
/usr/lib/libdb_cxx-4.8.a
/usr/lib/libdb_cxx-4.8.dll.a
/usr/lib/libdb_cxx-4.8.la
