/usr/bin/updmap-sys --nohash --nomkmap --disable cm-super-t1.map
/usr/bin/updmap-sys --nohash --nomkmap --disable cm-super-t2a.map
/usr/bin/updmap-sys --nohash --nomkmap --disable cm-super-t2b.map
/usr/bin/updmap-sys --nohash --nomkmap --disable cm-super-t2c.map
/usr/bin/updmap-sys --nohash --nomkmap --disable cm-super-ts1.map
/usr/bin/updmap-sys --nohash --nomkmap --disable cm-super-x2.map
/usr/bin/updmap-sys --nohash --nomkmap --disable eurosym.map
/usr/bin/updmap-sys --nohash --nomkmap --disable lm.map
/usr/bin/updmap-sys --nohash --nomkmap --disable marvosym.map
/usr/bin/updmap-sys --nohash --nomkmap --disable pxfonts.map
/usr/bin/updmap-sys --nohash --nomkmap --disable rsfs.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qag.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qbk.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qcr.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qcs.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qhv.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qpl.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qtm.map
/usr/bin/updmap-sys --nohash --nomkmap --disable qzc.map
/usr/bin/updmap-sys --nohash --nomkmap --disable tipa.map
/usr/bin/updmap-sys --nohash --nomkmap --disable txfonts.map
/usr/bin/updmap-sys --nohash --nomkmap --disable wasy.map
