ICU 4.8.1: stringpiece.h File Reference
stringpiece.h File Reference
C++ API: StringPiece: Read-only byte string wrapper class.
#include "unicode/utypes.h"
#include "unicode/uobject.h"
#include "unicode/std_string.h"
Data Structures
class StringPiece
A string-like object that points to a sized piece of memory.
Functions
U_EXPORT UBool operator== (const StringPiece &x, const StringPiece &y)
Global operator == for StringPiece.
UBool operator!= (const StringPiece &x, const StringPiece &y)
Global operator != for StringPiece.
Detailed Description
C++ API: StringPiece: Read-only byte string wrapper class.
Definition in file stringpiece.h.
Function Documentation
UBool operator!= (const StringPiece & x, const StringPiece & y) [inline]
Global operator != for StringPiece.
Parameters:
x The first StringPiece to compare.
y The second StringPiece to compare.
Returns:
TRUE if the string data is not equal
Draft:
This API may be changed in the future versions and was introduced in ICU 4.8
Definition at line 218 of file stringpiece.h.
U_EXPORT UBool operator== (const StringPiece & x, const StringPiece & y)
Global operator == for StringPiece.
Parameters:
x The first StringPiece to compare.
y The second StringPiece to compare.
Returns:
TRUE if the string data is equal
Draft:
This API may be changed in the future versions and was introduced in ICU 4.8
Referenced by TimeZone::operator!=(), RegexPattern::operator!=(), PluralRules::operator!=(), MessagePattern::Part::operator!=(), MessagePattern::operator!=(), FieldPositionIterator::operator!=(), Format::operator!=(), Formattable::operator!=(), DateFormatSymbols::operator!=(), DecimalFormatSymbols::operator!=(), Calendar::operator!=(), and BreakIterator::operator!=().